export const filterOptions = {
  years: ["All Years", "2025"],
  quarters: ["All Quarters", "Q1", "Q2", "Q3", "Q4"],
  categories: ["All Categories", "Education", "Public Speaking", "University Partnership"],
};

export const employees = [
  {
    id: "mira-solis",
    name: "Mira Solis",
    title: "Senior Software Engineer",
    code: "ORB.PF.ENG.1",
    avatarColor: "#2563eb",
    activities: [
      { activity: "AI Builder Workshop", category: "Public Speaking", date: "2025-12-17", points: 64 },
      { activity: "Prompt Patterns Digest #15", category: "Public Speaking", date: "2025-12-15", points: 16 },
      { activity: "Design Systems Deep Dive", category: "Education", date: "2025-11-12", points: 48 },
      { activity: "Campus Demo Day", category: "University Partnership", date: "2025-10-05", points: 64 },
      { activity: "AI Digest #11", category: "Public Speaking", date: "2025-10-26", points: 16 },
      { activity: "Engineering Knowledge Base Sprint", category: "Education", date: "2025-09-23", points: 48 },
      { activity: "Community Tech Session", category: "Public Speaking", date: "2025-09-08", points: 16 },
      { activity: "MCP Workshop", category: "Public Speaking", date: "2025-07-20", points: 64 },
      { activity: "Regional AI Training", category: "Public Speaking", date: "2025-07-11", points: 64 },
      { activity: "University Capstone Jury", category: "University Partnership", date: "2025-06-24", points: 48 },
      { activity: "Intro to AI Digest #1", category: "Public Speaking", date: "2025-05-27", points: 16 },
      { activity: "Cursor Lab", category: "Public Speaking", date: "2025-05-22", points: 64 },
      { activity: "Engineering Meetup Bratislava", category: "Public Speaking", date: "2025-05-14", points: 64 },
    ],
  },
  {
    id: "noah-kade",
    name: "Noah Kade",
    title: "Group Manager",
    code: "NOVA.GM.03",
    avatarColor: "#475569",
    activities: [
      { activity: "Leadership Roundtable", category: "Education", date: "2025-11-06", points: 96 },
      { activity: "Hiring University Panel", category: "University Partnership", date: "2025-10-10", points: 64 },
      { activity: "Mentor Office Hours", category: "Education", date: "2025-09-02", points: 48 },
      { activity: "Public Demo Review", category: "Public Speaking", date: "2025-08-19", points: 56 },
      { activity: "Team Enablement Session", category: "Education", date: "2025-07-04", points: 64 },
    ],
  },
  {
    id: "lara-quinn",
    name: "Lara Quinn",
    title: "Lead QA Engineer",
    code: "HELIOS.QA.01",
    avatarColor: "#b45309",
    activities: [
      { activity: "Testing Guild Session", category: "Education", date: "2025-12-03", points: 96 },
      { activity: "Quality Meet-up Talk", category: "Public Speaking", date: "2025-11-18", points: 64 },
      { activity: "Campus QA Workshop", category: "University Partnership", date: "2025-10-22", points: 64 },
      { activity: "Regression Clinic", category: "Education", date: "2025-09-10", points: 48 },
      { activity: "Automation Patterns", category: "Education", date: "2025-07-15", points: 48 },
    ],
  },
  {
    id: "owen-vale",
    name: "Owen Vale",
    title: "Lead QA Engineer",
    code: "HELIOS.QA.02",
    avatarColor: "#0f766e",
    activities: [
      { activity: "Quality Guild Facilitation", category: "Education", date: "2025-12-04", points: 112 },
      { activity: "Open Lecture on Reliability", category: "Public Speaking", date: "2025-10-20", points: 64 },
      { activity: "Testing Starter Kit", category: "Education", date: "2025-08-11", points: 48 },
      { activity: "Academic Collaboration Day", category: "University Partnership", date: "2025-05-30", points: 96 },
    ],
  },
  {
    id: "ivy-north",
    name: "Ivy North",
    title: "QA Engineer",
    code: "NIMBUS.QA.21",
    avatarColor: "#9333ea",
    activities: [
      { activity: "QA Foundations Class", category: "Education", date: "2025-12-09", points: 96 },
      { activity: "Conference Lightning Talk", category: "Public Speaking", date: "2025-09-18", points: 64 },
      { activity: "Mentorship Day", category: "University Partnership", date: "2025-06-06", points: 80 },
      { activity: "Testing Office Hours", category: "Education", date: "2025-05-02", points: 64 },
    ],
  },
  {
    id: "aria-stone",
    name: "Aria Stone",
    title: "Software Engineer",
    code: "ORBIT.FE.02",
    avatarColor: "#0ea5e9",
    activities: [
      { activity: "Frontend Patterns Workshop", category: "Education", date: "2025-11-25", points: 96 },
      { activity: "Design-to-Code Talk", category: "Public Speaking", date: "2025-08-08", points: 48 },
      { activity: "University Mock Interview", category: "University Partnership", date: "2025-06-19", points: 80 },
      { activity: "Accessibility Review Session", category: "Education", date: "2025-04-18", points: 72 },
    ],
  },
  {
    id: "jules-marin",
    name: "Jules Marin",
    title: "HR Manager",
    code: "PEOPLE.TAL.04",
    avatarColor: "#db2777",
    activities: [
      { activity: "Talent Growth Webinar", category: "Public Speaking", date: "2025-11-14", points: 96 },
      { activity: "University Career Day", category: "University Partnership", date: "2025-10-01", points: 64 },
      { activity: "People Ops Workshop", category: "Education", date: "2025-07-17", points: 64 },
      { activity: "Mentor Matching Program", category: "University Partnership", date: "2025-05-21", points: 64 },
    ],
  },
  {
    id: "nina-hale",
    name: "Nina Hale",
    title: "Senior QA Engineer",
    code: "AURORA.QA.09",
    avatarColor: "#7c3aed",
    activities: [
      { activity: "Exploratory Testing Lab", category: "Education", date: "2025-12-08", points: 96 },
      { activity: "Quality Meetup", category: "Public Speaking", date: "2025-10-16", points: 64 },
      { activity: "Student Project Critique", category: "University Partnership", date: "2025-05-09", points: 64 },
      { activity: "Bug Bash Facilitation", category: "Education", date: "2025-04-03", points: 64 },
    ],
  },
  {
    id: "ezra-frost",
    name: "Ezra Frost",
    title: "QA Engineer",
    code: "NIMBUS.QA.11",
    avatarColor: "#2563eb",
    activities: [
      { activity: "Automation Mini-Course", category: "Education", date: "2025-12-02", points: 96 },
      { activity: "Internal Tech Talk", category: "Public Speaking", date: "2025-09-05", points: 64 },
      { activity: "Campus Testing Sprint", category: "University Partnership", date: "2025-06-13", points: 64 },
      { activity: "Peer Learning Circle", category: "Education", date: "2025-03-20", points: 64 },
    ],
  },
  {
    id: "kai-rowe",
    name: "Kai Rowe",
    title: "Software Engineer",
    code: "ORBIT.API.08",
    avatarColor: "#dc2626",
    activities: [
      { activity: "API Design Class", category: "Education", date: "2025-11-20", points: 96 },
      { activity: "Tech Radar Talk", category: "Public Speaking", date: "2025-08-28", points: 64 },
      { activity: "Capstone Review", category: "University Partnership", date: "2025-05-15", points: 48 },
      { activity: "Internal Brown Bag", category: "Education", date: "2025-04-10", points: 48 },
    ],
  },
  {
    id: "theo-quade",
    name: "Theo Quade",
    title: "Senior Software Engineer",
    code: "PULSE.BE.14",
    avatarColor: "#1d4ed8",
    activities: [
      { activity: "Architecture Workshop", category: "Education", date: "2025-11-07", points: 96 },
      { activity: "Regional Engineering Talk", category: "Public Speaking", date: "2025-07-24", points: 64 },
      { activity: "University Systems Lecture", category: "University Partnership", date: "2025-04-25", points: 48 },
      { activity: "Platform Enablement", category: "Education", date: "2025-03-14", points: 48 },
    ],
  },
  {
    id: "mia-serrano",
    name: "Mia Serrano",
    title: "Software Engineer",
    code: "SOLAR.ML.06",
    avatarColor: "#15803d",
    activities: [
      { activity: "Applied AI Tutorial", category: "Education", date: "2025-10-30", points: 96 },
      { activity: "Student AI Clinic", category: "University Partnership", date: "2025-06-27", points: 64 },
      { activity: "Model Review Talk", category: "Public Speaking", date: "2025-05-29", points: 64 },
    ],
  },
  {
    id: "liam-crest",
    name: "Liam Crest",
    title: "Senior Software Engineer",
    code: "SOLAR.DATA.03",
    avatarColor: "#0f766e",
    activities: [
      { activity: "Data Platform Workshop", category: "Education", date: "2025-09-29", points: 96 },
      { activity: "Graduate Mentoring Panel", category: "University Partnership", date: "2025-07-03", points: 64 },
      { activity: "Observability Talk", category: "Public Speaking", date: "2025-03-27", points: 64 },
    ],
  },
  {
    id: "ava-mercer",
    name: "Ava Mercer",
    title: "QA Engineer",
    code: "POLAR.QA.15",
    avatarColor: "#2563eb",
    activities: [
      { activity: "Quality Metrics Session", category: "Education", date: "2025-10-09", points: 96 },
      { activity: "Campus Reliability Week", category: "University Partnership", date: "2025-06-05", points: 64 },
      { activity: "Release Readiness Talk", category: "Public Speaking", date: "2025-02-13", points: 48 },
    ],
  },
  {
    id: "max-porter",
    name: "Max Porter",
    title: "Senior Software Engineer",
    code: "AETHER.AI.02",
    avatarColor: "#7c3aed",
    activities: [
      { activity: "Machine Learning Lab", category: "Education", date: "2025-08-21", points: 96 },
      { activity: "Research Partner Session", category: "University Partnership", date: "2025-06-12", points: 64 },
      { activity: "Innovation Demo", category: "Public Speaking", date: "2025-01-30", points: 64 },
    ],
  },
];